from decouple import config

ENV = config("ENVIRONMENT", default="DEV")

MONGO_CONNECTION_STRING = config("MONGO_CONNECTION_STRING")
CAPTCHA_SOLVER_API_KEY = config("CAPTCHA_SOLVER_API_KEY")
CAPTCHA_SOLVER_URL = config("CAPTCHA_SOLVER_URL")
